import {
  faAnchor,
  faBaby,
  faBaseball,
  faBasketball,
  faBicycle,
  faBook,
  faBowlingBall,
  faBriefcaseMedical,
  faBurger,
  faCakeCandles,
  faCapsules,
  faCar,
  faCartShopping,
  faChild,
  faCircleQuestion,
  faCoffee,
  faCookie,
  faCouch,
  faDice,
  faDollarSign,
  faDumbbell,
  faFaceSmile,
  faFerry,
  faFilm,
  faFire,
  faFlask,
  faFootball,
  faGamepad,
  faGears,
  faGift,
  faGraduationCap,
  faHandHoldingDollar,
  faHandshake,
  faHeadphones,
  faHeartPulse,
  faHospital,
  faHouse,
  faIceCream,
  faLandmark,
  faLaptopCode,
  faLaptopFile,
  faLeaf,
  faLightbulb,
  faMartiniGlassCitrus,
  faMoneyBill,
  faMoneyBillTrendUp,
  faMusic,
  faNewspaper,
  faPaperPlane,
  faPaw,
  faPeopleGroup,
  faPersonDigging,
  faPhone,
  faPiggyBank,
  faPlaneDeparture,
  faPrint,
  faRadio,
  faSackDollar,
  faScaleBalanced,
  faScrewdriverWrench,
  faSeedling,
  faShip,
  faSmoking,
  faSolarPanel,
  faSuitcaseMedical,
  faSyringe,
  faTableTennisPaddleBall,
  faTaxi,
  faTicket,
  faToiletPaper,
  faTooth,
  faTrain,
  faTruck,
  faUtensils,
  faVolleyball,
  faWeightHanging,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export const iconObject = {
  faCoffee: <FontAwesomeIcon icon={faCoffee} />,
  faUtensils: <FontAwesomeIcon icon={faUtensils} />,
  faBurger: <FontAwesomeIcon icon={faBurger} />,
  faCakeCandles: <FontAwesomeIcon icon={faCakeCandles} />,
  faMartiniGlassCitrus: <FontAwesomeIcon icon={faMartiniGlassCitrus} />,
  faIceCream: <FontAwesomeIcon icon={faIceCream} />,
  faCookie: <FontAwesomeIcon icon={faCookie} />,
  faCar: <FontAwesomeIcon icon={faCar} />,
  faTruck: <FontAwesomeIcon icon={faTruck} />,
  faTaxi: <FontAwesomeIcon icon={faTaxi} />,
  faFerry: <FontAwesomeIcon icon={faFerry} />,
  faAnchor: <FontAwesomeIcon icon={faAnchor} />,
  faTrain: <FontAwesomeIcon icon={faTrain} />,
  faPlaneDeparture: <FontAwesomeIcon icon={faPlaneDeparture} />,
  faPaperPlane: <FontAwesomeIcon icon={faPaperPlane} />,
  faShip: <FontAwesomeIcon icon={faShip} />,
  faBicycle: <FontAwesomeIcon icon={faBicycle} />,
  faBriefcaseMedical: <FontAwesomeIcon icon={faBriefcaseMedical} />,
  faSuitcaseMedical: <FontAwesomeIcon icon={faSuitcaseMedical} />,
  faHeartPulse: <FontAwesomeIcon icon={faHeartPulse} />,
  faTooth: <FontAwesomeIcon icon={faTooth} />,
  faSyringe: <FontAwesomeIcon icon={faSyringe} />,
  faFlask: <FontAwesomeIcon icon={faFlask} />,
  faHospital: <FontAwesomeIcon icon={faHospital} />,
  faCapsules: <FontAwesomeIcon icon={faCapsules} />,
  faLaptopFile: <FontAwesomeIcon icon={faLaptopFile} />,
  faLaptopCode: <FontAwesomeIcon icon={faLaptopCode} />,
  faPhone: <FontAwesomeIcon icon={faPhone} />,
  faPrint: <FontAwesomeIcon icon={faPrint} />,
  faRadio: <FontAwesomeIcon icon={faRadio} />,
  faNewspaper: <FontAwesomeIcon icon={faNewspaper} />,
  faDumbbell: <FontAwesomeIcon icon={faDumbbell} />,
  faTableTennisPaddleBall: <FontAwesomeIcon icon={faTableTennisPaddleBall} />,
  faBasketball: <FontAwesomeIcon icon={faBasketball} />,
  faBowlingBall: <FontAwesomeIcon icon={faBowlingBall} />,
  faFootball: <FontAwesomeIcon icon={faFootball} />,
  faWeightHanging: <FontAwesomeIcon icon={faWeightHanging} />,
  faVolleyball: <FontAwesomeIcon icon={faVolleyball} />,
  faBaseball: <FontAwesomeIcon icon={faBaseball} />,
  faSmoking: <FontAwesomeIcon icon={faSmoking} />,
  faGamepad: <FontAwesomeIcon icon={faGamepad} />,
  faDice: <FontAwesomeIcon icon={faDice} />,
  faTicket: <FontAwesomeIcon icon={faTicket} />,
  faFilm: <FontAwesomeIcon icon={faFilm} />,
  faMusic: <FontAwesomeIcon icon={faMusic} />,
  faHeadphones: <FontAwesomeIcon icon={faHeadphones} />,
  faBaby: <FontAwesomeIcon icon={faBaby} />,
  faChild: <FontAwesomeIcon icon={faChild} />,
  faPeopleGroup: <FontAwesomeIcon icon={faPeopleGroup} />,
  faPersonDigging: <FontAwesomeIcon icon={faPersonDigging} />,
  faFaceSmile: <FontAwesomeIcon icon={faFaceSmile} />,
  faBook: <FontAwesomeIcon icon={faBook} />,
  faGraduationCap: <FontAwesomeIcon icon={faGraduationCap} />,
  faHouse: <FontAwesomeIcon icon={faHouse} />,
  faCouch: <FontAwesomeIcon icon={faCouch} />,
  faToiletPaper: <FontAwesomeIcon icon={faToiletPaper} />,
  faLightbulb: <FontAwesomeIcon icon={faLightbulb} />,
  faCartShopping: <FontAwesomeIcon icon={faCartShopping} />,
  faGift: <FontAwesomeIcon icon={faGift} />,
  faLeaf: <FontAwesomeIcon icon={faLeaf} />,
  faSeedling: <FontAwesomeIcon icon={faSeedling} />,
  faPaw: <FontAwesomeIcon icon={faPaw} />,
  faDollarSign: <FontAwesomeIcon icon={faDollarSign} />,
  faMoneyBillTrendUp: <FontAwesomeIcon icon={faMoneyBillTrendUp} />,
  faPiggyBank: <FontAwesomeIcon icon={faPiggyBank} />,
  faSackDollar: <FontAwesomeIcon icon={faSackDollar} />,
  faMoneyBill: <FontAwesomeIcon icon={faMoneyBill} />,
  faHandshake: <FontAwesomeIcon icon={faHandshake} />,
  faHandHoldingDollar: <FontAwesomeIcon icon={faHandHoldingDollar} />,
  faLandmark: <FontAwesomeIcon icon={faLandmark} />,
  faScaleBalanced: <FontAwesomeIcon icon={faScaleBalanced} />,
  faGears: <FontAwesomeIcon icon={faGears} />,
  faScrewdriverWrench: <FontAwesomeIcon icon={faScrewdriverWrench} />,
  faFire: <FontAwesomeIcon icon={faFire} />,
  faCircleQuestion: <FontAwesomeIcon icon={faCircleQuestion} />,
};
